import Head from 'next/head';
import HeaderComponent from '@/components/HeaderComponent';
import ProductsComponent from '@/components/ProductsComponent';
import FooterComponent from '@/components/FooterComponent';
import CarousalsComponent from '@/components/home-screen/CarousalsComponent';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Takealot.com</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderComponent />
            <CarousalsComponent />
            <div className='bg-gray-100 pt-2 pb-6'>
                <ProductsComponent title='Load Shedding Essentials'/>
                <ProductsComponent title='New on Takealot'/>
                <ProductsComponent title='Your Premium Liquor Choices'/>
                <ProductsComponent title='Makeup'/>
                <ProductsComponent title='Sports & Training'/>
            </div>
            <FooterComponent /> 
        </div>
    )
}
